apiVersion: apps/v1
kind: Deployment
metadata: 
   name: webserver
   labels:
      pod: dev
      region: IN
spec:
   replicas: 2
   selector:
      matchLabels:
        pod: dev
        region: IN
   template:
    metadata:
       labels:
          pod: dev
          region: IN
    spec:
      containers:
      - name: webserver
        image: premchandg278/webserver:v4
        ports:
        - containerPort: 80