apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003
    protocol: TCP
    name: webserver-port
  selector:
      pod: dev
      region: IN